baseURL = 'https://www.zacharyparmley.com/'
languageCode = 'en-us'
title = 'Zachary C. Parmley'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.147.0'

# [Taxonomies]

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Snippets'
    pageRef = '/snippets'
    weight = 20
  
  [[menus.main]]
    name = 'Cameras'
    pageRef = '/cameras'
    weight = 30

  [[menus.main]]
    name = 'Resume'
    pageRef = '/resume'
    weight = 40


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
