[project]
name = "zacharyparmley-com"
version = "0.1.0"
description = "Zachary Parmley's personal website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-fasthtml>=0.12.19",
]
